Refactoring
cgogolin/quantum-journal pull request #65
Opened 2019-02-04 20:22 UTC by johannesjmeyer

Merging this using the code compare could be somewhat tedious because the changes are so widespread. I suggest to checkout the refactoring branch and have a look there.

2019-02-04 20:31 UTC, johannesjmeyer commented
I also caught the misspelling of "allowfontchangeintitle"

2019-03-02 20:03 UTC, cgogolin requested changes
This is already looking good. I suggested some further changes and have a few wishes. The only thing critical is prefixing the toggles with @ to avoid clashes with user-defined macros.

2019-03-02 20:03 UTC, cgogolin commented on quantumarticle.cls
> +	class for Quantum - the open journal for quantum science (http://quantum-journal.org)]
```suggestion
class for Quantum - the open journal for quantum science (http://quantum-journal.org)]
```
Does the leading space here serve any purpose? If not we should get rid of it as well.

2019-03-02 20:03 UTC, cgogolin commented on quantumarticle.cls
>  	\ClassError{quantumarticle}{ Please specify a paper size. Available options: a4paper, a5paper, b5paper, letterpaper, legalpaper, executivepaper }{}
```suggestion
	\ClassError{quantumarticle}{Please specify a paper size. Available options: a4paper, a5paper, b5paper, letterpaper, legalpaper, executivepaper}{}
```

2019-03-02 20:03 UTC, cgogolin commented on quantumarticle.cls
> +			\ifnum \c@secnumdepth >\z@
Do you think we could replace all `\ifnum`s by `\ifnumcomp`s as part of this refactor? I see that you already did this is many places, but maybe it is worth doing this consistently?

2019-03-02 20:03 UTC, cgogolin commented on quantumarticle.cls
> +\newtoggle{restonecol}
The old ifs had a @ prefix to hide them from users and avoide conflicts with user-defined macros. I think it would be good to do that for the toggles as well. Can we consistently prefix all toggles with an @ ?

2019-03-02 20:03 UTC, cgogolin commented on quantumarticle.cls
> +\DeclareOptionX{onecolumn}{\@twocolumnfalse}
Is there a reason why we can't use a toogle here as well? Maybe because ltxgrid uses this if? If so, would it be "cleaner" to define a toggle and an if, put a comment behind the if explaining why it is necessary and the only use the toggle in this file?

2019-03-02 20:03 UTC, cgogolin commented on quantumarticle.cls
> +			\ClassWarning{quantumarticle}{Unfortunately the quantumarticle can not recommend the use of biblatex due to incompatibilities between locally installed versions of biblatex and the version used by
```suggestion
			\ClassWarning{quantumarticle}{Unfortunately quantumarticle cannot recommend the use of BibLaTeX due to incompatibilities between locally installed versions of BibLaTeX and the version used by the arXiv.}%
```

2019-03-03 12:31 UTC, johannesjmeyer commented on quantumarticle.cls
> +\newtoggle{restonecol}
Totally with you now, we can prefix them with @s, I'll do that.

2019-03-03 12:35 UTC, johannesjmeyer commented on quantumarticle.cls
> +\DeclareOptionX{onecolumn}{\@twocolumnfalse}
Yes, this is a command defined externally, so I didn't touch it. I had a look in the etoolbox specification and we can just use the `bool` interface to manipulate and check variables previously defined with `\newif`. I'll add that to my todo-list.

2019-03-03 12:36 UTC, johannesjmeyer commented on quantumarticle.cls
> +\DeclareOptionX{onecolumn}{\@twocolumnfalse}
So we can just use `\boolfalse{@twocolumn}`

2019-03-03 12:38 UTC, johannesjmeyer commented on quantumarticle.cls
> +			\ifnum \c@secnumdepth >\z@
I think we can, but I have to check first if it really works in the same way. I suppose there could be some problems with the order in which commands are expanded. I will run some tests and then see. But as this command is a wrapper for `\ifnum` it should work out in the end.

2019-03-03 12:41 UTC, johannesjmeyer commented
Just to summarise what's left on the list for this commit:

- Let all toggles start with an @ 
- Have a look at the expansion of `ifnumcomp` and replace `\ifnum` with it if possible
- Use the `bool` interface from `etoolbox` to manipulate external variables (`@twocolumn`)

2019-03-13 09:50 UTC, cgogolin approved these changes
Perfect.

2019-03-13 09:52 UTC, merged